# Generated by Django 4.2.16 on 2025-09-30 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='characterspell',
            unique_together={('character', 'spell')},
        ),
        migrations.AlterUniqueTogether(
            name='characterskill',
            unique_together={('character', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='charactersavingthrow',
            unique_together={('character', 'ability_name')},
        ),
        migrations.AlterUniqueTogether(
            name='characterproficiency',
            unique_together={('character', 'proficiency_type', 'proficiency_name')},
        ),
        migrations.AlterUniqueTogether(
            name='characterlanguage',
            unique_together={('character', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='characterfeature',
            unique_together={('character', 'class_feature')},
        ),
        migrations.AlterUniqueTogether(
            name='characterfeat',
            unique_together={('character', 'feat', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='characterequipment',
            unique_together={('character', 'equipment')},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('user', 'character_name')},
        ),
    ]
